<#
  Registers a Windows Scheduled Task that starts the agent-bridge bot at logon.

  Why a Windows task rather than systemd inside WSL: a service inside the distro
  only runs while the distro is up. After a Windows reboot the distro is not
  running at all until something starts it, so the trigger has to live on the
  Windows side. This task starts the distro AND the bot.

  Run from PowerShell (no admin needed):
      .\scripts\install_autostart.ps1
      .\scripts\install_autostart.ps1 -Uninstall
#>
param(
  [string]$Distro   = "Ubuntu-24.04",
  [string]$TaskName = "agent-bridge-bot",
  [switch]$Uninstall
)
$ErrorActionPreference = "Stop"

if ($Uninstall) {
  if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Output "removed scheduled task '$TaskName'"
  } else { Write-Output "no scheduled task '$TaskName' found" }
  exit 0
}

# Repo root = parent of this script's directory, as Windows and WSL paths.
$repoWin = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$drive   = $repoWin.Substring(0,1).ToLower()
$repoWsl = "/mnt/$drive" + $repoWin.Substring(2).Replace('\','/')
Write-Output "repo (windows): $repoWin"
Write-Output "repo (wsl)    : $repoWsl"

$wslUser = (wsl -d $Distro -- whoami).Trim()
if (-not $wslUser) { throw "could not determine the WSL user for distro '$Distro'" }
Write-Output "wsl user      : $wslUser"

# A tiny VBS shim launches wsl.exe with no console window, so logon stays clean.
$stateDir = Join-Path $env:USERPROFILE ".agent-bridge"
New-Item -ItemType Directory -Force -Path $stateDir | Out-Null
$vbs = Join-Path $stateDir "launch.vbs"
$cmd = "wsl.exe -d $Distro -u $wslUser -- bash -lc ""$repoWsl/scripts/bot_ctl.sh start"""
# VBS represents a literal quote inside a string as two quotes, so every " in the
# command has to be doubled before it is embedded below. Without this the VBS
# string terminates early at `bash -lc ` and the script is a syntax error.
$cmdVbs = $cmd -replace '"', '""'
@"
' Generated by agent-bridge install_autostart.ps1 - launches the bot with no visible window.
CreateObject("WScript.Shell").Run "$cmdVbs", 0, False
"@ | Set-Content -Path $vbs -Encoding ASCII
Write-Output "launcher      : $vbs"

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
  Write-Output "(replaced existing task)"
}

$action   = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$vbs`""
$trigger  = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries `
              -DontStopIfGoingOnBatteries -StartWhenAvailable `
              -ExecutionTimeLimit ([TimeSpan]::Zero)

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
  -Settings $settings -Description "Starts the agent-bridge Discord bot inside WSL at logon." | Out-Null

Write-Output ""
Write-Output "registered scheduled task '$TaskName' (runs at your logon)"
Write-Output "  start it now : Start-ScheduledTask -TaskName $TaskName"
Write-Output "  check        : wsl -d $Distro -- $repoWsl/scripts/bot_ctl.sh status"
Write-Output "  remove       : .\scripts\install_autostart.ps1 -Uninstall"
